version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/unisolve-be
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: scripts/app_stop.sh
      timeout: 300
  ApplicationStart:
   - location: scripts/app_start.sh
     timeout: 300
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file