export const speeches = {
    WELCOME_MESSAGE: "Welcome to the Unisolve APIs",
    UNABLE_TO_CREATE_TOKEN: "Unable to create token",
    INVALID_DATA_SEND_TO_CREATE_TOKEN: "Invalid data send to create token",
    INVALID_TOKEN: "Invalid token! Kindly provide a valid token",
    UNAUTHORIZED_ACCESS: "Unauthorized Access! Kindly provide a valid token",
    TOKEN_EXPIRED: "Token Expired! Kindly provide a valid token",
    BAD_REQUEST: "Bad Request",
    NOT_ACCEPTABLE: "Not Acceptable",
    DATA_NOT_FOUND: "Data not found",
    USER_NOT_FOUND: "User not found",
    USER_RISTRICTED: "Unauthorized Access!",
    USER_DELETED: "User is ditected as deleted. Kindly contact your administrator.",
    USER_LOCKED: "User is ditected as locked. Kindly contact your administrator.",
    USER_INACTIVE: "User is ditected as inactive. Kindly contact your administrator.",
    USER_ALREADY_EXISTED: "User already existed with the Email and Phone Number.",
    USER_REGISTERED_SUCCESSFULLY: "User registered successfully",
    USER_LOGIN_SUCCESS: "Login Successful",
    LOGOUT_SUCCESS: "Logout Successful",
    USER_EMAIL_REQUIRED: "Email is required, it should not be empty.",
    USER_EMAIL_INVALID: "Email is invalid, it should be a valid email.",
    USER_PWD_REQUIRED: "Password is required, it should not be empty.",
}
